---
- name: create /etc/mesos-master
  file: >-
    owner=root
    group=root
    mode=755
    path=/etc/mesos-master
    state=directory

- name: install /etc/mesos-master/* files
  template: >
    src=etc/mesos-master/{{item}}.j2
    dest=/etc/mesos-master/{{item}}
    owner=root
    group=root
    mode=0644
  with_items:
    - quorum
    - hostname
    - ip

- name: install mesosmaster
  package: state=present name=mesos

